on: [pull_request]

name: Rust-Checks

jobs:
  cargo_check:
    name: Cargo Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-09-04
          default: true
          target: thumbv7em-none-eabihf
      - name: Cargo Check
        run: cd control && cargo check --examples --bins --lib --target thumbv7em-none-eabihf

  cargo_clippy:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-09-04
          default: true
          target: thumbv7em-none-eabihf
          components: clippy
      - name: Run Clippy
        run: cd control && cargo clippy --target thumbv7em-none-eabihf

  cargo_build:
    name: Cargo Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-09-04
          default: true
          target: thumbv7em-none-eabihf
      - name: Run Cargo Build
        run: cd control && cargo build --release --examples --bins --lib --target thumbv7em-none-eabihf

  cargo_rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v4
      - name: Setup Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-09-04
          default: true
          target: thumbv7em-none-eabihf
          components: rustfmt
      - name: Run rustfmt
        run: cd control && cargo fm --check
